### ISSUE TITLE
Future Enhancements after Solution challenge 

### ISSUE THREAD

**Issue by A7med7x7** [A7med7x7/Tesnor-Flow-SC-Fertilizer-and-Crop-Recommendation-Recomm#1]
we can work on what we needed to do in the repository but we delayed it. 

### we can start with 

1. the name of our app—you guys remember the gezira and gazira arguments we had? **@Asmaa6777**  can search for the best naming so we can build on top of that
2. **@MaabTaha** and I can work on making the repository easy to navigate and use. 

![yes](https://media.giphy.com/media/CjmvTCZf2U3p09Cn0h/giphy.gif)

**Comment by A7med7x7** [comment]
@MaabTaha can you think of ideal name for the repository, Probably we were rejected because of that 🤣

**Comment by MaabTaha** [comment]
Got it😂
